Repository passwordless-lib/fido2-net-lib, pull requests merged in 2021-03, with the labels that each got.

#208 change origin verify to use fully qualified origin
  Src/Fido2/AuthenticatorResponse.cs
Labels: bug

#211 Revert "change origin verify to use fully qualified origin"
  Src/Fido2/AuthenticatorResponse.cs
Labels: bug

#188 MDS error handling and cache-friendlieness refactoring
  Demo/Startup.cs
  Src/Fido2.AspNet/DistributedCacheMetadataService.cs
  Src/Fido2.Models/Metadata/MetadataTOCPayload.cs
  Src/Fido2/IMetadataRepository.cs
  Src/Fido2/Metadata/ConformanceMetadataRepository.cs
  Src/Fido2/Metadata/Fido2MetadataServiceRepository.cs
  Src/Fido2/Metadata/FileSystemMetadataRepository.cs
  Src/Fido2/Metadata/StaticMetadataRepository.cs
  Src/Fido2/SimpleMetadataService.cs
  Test/MetadataServiceTests.cs
Labels: enhancement

#205 Attestation refactor, implement Apple attestation format verifier
  Src/Fido2/AttestationFormat/AndroidKey.cs
  Src/Fido2/AttestationFormat/AndroidSafetyNet.cs
  Src/Fido2/AttestationFormat/Apple.cs
  Src/Fido2/AttestationFormat/AttestationFormat.cs
  Src/Fido2/AttestationFormat/FidoU2f.cs
  Src/Fido2/AttestationFormat/None.cs
  Src/Fido2/AttestationFormat/Packed.cs
  Src/Fido2/AttestationFormat/Tpm.cs
  Src/Fido2/AuthenticatorAttestationResponse.cs
  Src/Fido2/CryptoUtils.cs
  Src/Fido2/Metadata/StaticMetadataRepository.cs
  Src/Fido2/Objects/AttestationType.cs
  Test/Attestation/Apple.cs
  Test/Attestation/Tpm.cs
  Test/Fido2Tests.cs
  Test/TestFiles/attestationAppleOptions.json
  Test/TestFiles/attestationAppleResponse.json
Labels: enhancement

#175 Release version 2.0.0
  Demo/Startup.cs
  Directory.Build.props
  Src/Fido2.AspNet/DistributedCacheMetadataService.cs
  Src/Fido2.Models/Metadata/MetadataTOCPayload.cs
  Src/Fido2/AttestationFormat/Tpm.cs
  Src/Fido2/IMetadataRepository.cs
  Src/Fido2/Metadata/ConformanceMetadataRepository.cs
  Src/Fido2/Metadata/Fido2MetadataServiceRepository.cs
  Src/Fido2/Metadata/FileSystemMetadataRepository.cs
  Src/Fido2/Metadata/StaticMetadataRepository.cs
  Src/Fido2/SimpleMetadataService.cs
  Test/Attestation/Tpm.cs
  Test/MetadataServiceTests.cs
Labels: chore

#207 Release 2.0.0 (2021)
  Test/Attestation/Tpm.cs
Labels: chore

#213 change origin verify to use fully qualified origin
  Src/Fido2/AuthenticatorResponse.cs
Labels: duplicate, enhancement
