Repository passwordless-lib/fido2-net-lib, pull requests merged in 2021-11, with the labels that each got.

#259 Improve Code Quality 5
  Src/Fido2/AttestationFormat/AndroidKey.cs
  Src/Fido2/AttestationFormat/AndroidSafetyNet.cs
  Src/Fido2/AttestationFormat/Apple.cs
  Src/Fido2/AttestationFormat/AttestationFormat.cs
  Src/Fido2/AttestationFormat/FidoU2f.cs
  Src/Fido2/AttestationFormat/Packed.cs
  Src/Fido2/AttestationFormat/Tpm.cs
  Src/Fido2/AuthenticatorAssertionResponse.cs
  Src/Fido2/AuthenticatorAttestationResponse.cs
  Src/Fido2/Cbor/CborObject.cs
  Src/Fido2/DateTimeHelper.cs
  Src/Fido2/Extensions/DataHelper.cs
  Src/Fido2/Metadata/ConformanceMetadataRepository.cs
  Src/Fido2/Objects/AttestedCredentialData.cs
  Src/Fido2/Objects/CredentialIdUserHandleParams.cs
  Src/Fido2/Objects/CredentialIdUserParams.cs
  Src/Fido2/Objects/CredentialPublicKey.cs
  Test/Attestation/AndroidSafetyNet.cs
  Test/Attestation/Apple.cs
  Test/Attestation/Tpm.cs
  Test/ExistingU2fRegistrationDataTests.cs
  Test/Fido2Tests.cs
Labels: enhancement, chore

#262 Fix old links in readme
  README.md
Labels: chore

#261 Fix attestation certificate validation
  Src/Fido2/CryptoUtils.cs
  Test/CryptoUtilsTests.cs
Labels: bug, enhancement, chore

#237 Support Multiple Origins
  Demo/Startup.cs
  Demo/TestController.cs
  Src/Fido2.Models/Fido2Configuration.cs
  Src/Fido2.Models/StringExtensions.cs
  Src/Fido2/AuthenticatorAssertionResponse.cs
  Src/Fido2/AuthenticatorAttestationResponse.cs
  Src/Fido2/AuthenticatorResponse.cs
  Src/Fido2/Fido2NetLib.cs
  Test/Attestation/Apple.cs
  Test/AuthenticatorResponse.cs
  Test/ExistingU2fRegistrationDataTests.cs
  Test/Fido2Tests.cs
Labels: enhancement, feature
