Repository passwordless-lib/fido2-net-lib, pull requests merged in 2023-08, with the labels that each got.

#412 [WIP] Make AuthenticatorData immutable and strongly type throughout library
  Src/Fido2.Models/Objects/AttestationVerificationSuccess.cs
  Src/Fido2/AttestationFormat/AndroidKey.cs
  Src/Fido2/AttestationFormat/Apple.cs
  Src/Fido2/AttestationFormat/AppleAppAttest.cs
  Src/Fido2/AttestationFormat/AttestationVerifier.cs
  Src/Fido2/AttestationFormat/FidoU2f.cs
  Src/Fido2/AttestationFormat/Packed.cs
  Src/Fido2/AttestationFormat/Tpm.cs
  Src/Fido2/AuthenticatorAssertionResponse.cs
  Src/Fido2/AuthenticatorAttestationResponse.cs
  Src/Fido2/AuthenticatorResponse.cs
  Src/Fido2/Fido2.csproj
  Src/Fido2/Objects/AuthenticatorData.cs
  Src/Fido2/Objects/CredentialIdUserHandleParams.cs
  Src/Fido2/Objects/CredentialIdUserParams.cs
  Test/Asn1Tests.cs
  Test/Attestation/Tpm.cs
  Test/AuthenticatorDataTests.cs
  Test/AuthenticatorResponse.cs
  Test/Fido2Tests.cs
  Test/Test.csproj
  Tests/Fido2.Ctap2.Tests/Fido2.Ctap2.Tests.csproj
Labels: enhancement

#409 Add .bool to Output aswell
  Src/Fido2.Models/Objects/AuthenticationExtensionsClientOutputs.cs
Labels: bug

#410 Added Enterprise attestation
  Demo/Pages/_options.cshtml
  Src/Fido2.Models/Objects/AttestationConveyancePreference.cs
Labels: feature

#413 Prefer Ed25519 when available
  Src/Fido2.Models/CredentialCreateOptions.cs
Labels: enhancement

#411 Add CredentialPropertiesOuput (RK Support)
  Demo/Controller.cs
  Src/Fido2.Models/Objects/AuthenticationExtensionsClientOutputs.cs
  Src/Fido2.Models/Objects/CredentialPropertiesOutput.cs
Labels: enhancement
